### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JulioLeonIncio** [xmc811/Scillus#10]
**Describe the bug**
I get some genes out of the marker genes as NA
![image](https://user-images.githubusercontent.com/23158173/124060942-fb26a580-da68-11eb-9291-759fa1e65a23.png)

thank you!

Julio

**Comment by xmc811** [comment]
Would you please check which data slot those NA genes are in? Currently, the function gets gene data from `DefaultAssay()` and `"scale.data"`:

`mat <- GetAssayData(object = dataset, assay = DefaultAssay(dataset), slot = "scale.data")`

**Comment by JulioLeonIncio** [comment]
Thanks for your response. I confirmed that the genes are not on the scale. data slot. Any change to make slot data modifiable in your function?

**Comment by JulioLeonIncio** [comment]
problem solved:
![image](https://user-images.githubusercontent.com/23158173/124379109-03dcdd00-dcf0-11eb-988c-612cf42c798b.png)
thanks,
Julio
