### ISSUE TITLE
Support of more colors than possible with RColorBrewer[Feature]

### ISSUE THREAD

**Issue by Sirt0r** [xmc811/Scillus#3]
The limitation of RColorBrewer palettes to max 12 colors is kind of annoying. Do you think you might be able to create support for custom color lists or color palettes with more variations?
Or is there a workaround that I don't see?

**Comment by xmc811** [comment]
@Sirt0r
Thank you very much for your suggestion. The package has been updated to include these features.

For example, in the `pal_setup`, you can do `c("Set2, "Set3")` to include colors of both palettes, and you can also simply input a color vector of any length. Please refer to https://scillus.netlify.app/vignettes/plotting.html for more details.
