### ISSUE TITLE
elements in `col` should be named vectors

### ISSUE THREAD

**Issue by kaizen89** [xmc811/Scillus#5]
Hi, 
I have a strange error when I input specific colors in anno_colors .
```
if : anno_colors = list(c("Set1","Set3","Set2"), "Set2",pal1),  # works fine
if:  anno_colors = list(c("Set1","Set3","Set2"),pal1, "Set2") # error: Error: elements in `col` should be named vectors.

Any suggestion?
Thanks

**Comment by xmc811** [comment]
@kaizen89 
Thank you for the feedback. May I know what's the `pal1` in your code? And are the variables in `anno_var` numeric or character? I suspect these might be the problems.

**Comment by kaizen89** [comment]
`Pal1` is a vector of hex color codes. The issue is happening both for numeric and character variables.

**Comment by xmc811** [comment]
@kaizen89 
It would be better if I have the code of your complete function call, and please let me know the types of `anno_var`

**Comment by kaizen89** [comment]
Sure
```
plot_heatmap(seurat_small, markers =c(genes,unique(topgenes)),sort_var = c("seurat_clusters","dataset","patient_ID"),
              anno_var = c("seurat_clusters","dataset","patient_ID"),
              anno_colors = list(pal1,"Set1","Set2"),
              hm_colors = c("purple","black","yellow"))
pal1
[1] "#B10DA1" "#0000FF" "#FF0000" "#00FF00" "#000033" "#005300" "#FFD300" "#009FFF" "#9A4D42" "#00FFBE" "#783FC1" "#1F9698"
[13] "#FFACFD" "#B1CC71" "#FE8F42" "#DD00FF" "#766C95" "#02AD24" "#C8FF00" "#886C00" "#FFB79F" "#858567" "#A10300" "#14F9FF"
[25] "#00479E" "#DC5E93" "#93D4FF" "#004CFF" "#F2F318"
```
`Seurat_clusters` are integers, `dataset` et `patient_ID` are character variables.

Thanks

**Comment by xmc811** [comment]
@kaizen89 
The bug should be fixed now.

**Comment by kaizen89** [comment]
It works for character variables, that should do it. Thanks

**Comment by kaizen89** [comment]
I was too fast, it actually works also for numerical variables
