### ISSUE TITLE
Display legend top annotation the same way as in Seurat

### ISSUE THREAD

**Issue by kaizen89** [xmc811/Scillus#7]
Would it be possible to display the clusters annotation (or ideally the first annotation variable) the same way as in Seurat? Clusters on top of the annotation bar with 45 degree angle.
Sorry if it's too much to ask, but this could also save space on the right of the heatmap for more annotations without overlapping them.

**Comment by kaizen89** [comment]
I have been able to generate this by modifying the `plot_heatmap` funtion, the only missing thing is the rotation of the cluster lables.
![image](https://user-images.githubusercontent.com/30392707/115401764-6a735400-a1f3-11eb-9321-d458836dc74f.png)

**Comment by xmc811** [comment]
@kaizen89 
If you are able to modify the function on your own, you can adjust `column_title_rot` parameter in the `Heatmap()` function call to do the rotation of cluster labels.

**Comment by kaizen89** [comment]
Thanks for the tip. I can now rotate the labels vertically (not possible for 45' angle). The only issue is that the labels are  a bit cropped. If I put cell_type names it's even worse.
![image](https://user-images.githubusercontent.com/30392707/115541263-9a7c2f00-a2a7-11eb-8c70-6bd48ea33d7f.png)

**Comment by xmc811** [comment]
@kaizen89 
You can also modify the function:
https://github.com/jokergoo/ComplexHeatmap/issues/509#issuecomment-642475140
