### ISSUE TITLE
Decrease height of column annotation

### ISSUE THREAD

**Issue by kaizen89** [xmc811/Scillus#8]
Hi,
I am trying to decrease the height of column annotation using `annotation_height` but this does not seem to work.
![image](https://user-images.githubusercontent.com/30392707/119480753-a5b8f380-bd5a-11eb-9f53-49c9da258bda.png)
Any idea how to do this? Thanks

**Comment by kaizen89** [comment]
I should have used `simple_anno_size` instead of `annotation_height`. However, the height of the continuous variable `lognUMI` seems unchanged.
![image](https://user-images.githubusercontent.com/30392707/119489910-df8ef780-bd64-11eb-9550-16dfce14b2ea.png)

**Comment by xmc811** [comment]
If you are modifying the `plot_heatmap()` function internally, it seems to be a question for `ComplexHeatmap` itself.
